### ISSUE TITLE
Increase contrast between text and background colors

### ISSUE THREAD

**Issue by archshift** [ziacko/SPIRV-viewer#1]
As it stands, it's rather hard to read the text on the screen since it doesn't contrast well with the background. A simple solution would be to just make the background colors darker.

**Comment by ziacko** [comment]
![capture2](https://cloud.githubusercontent.com/assets/3490388/17276148/326ceaba-5763-11e6-8ab3-d1a033095d4a.PNG)
like this or a little lighter?

**Comment by archshift** [comment]
I personally think that's great!

**Comment by ziacko** [comment]
ok it's in the latest commit
